asv:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  # Effort Controllers ---------------------------------------
  left_thruster_controller:
    type: effort_controllers/JointEffortController
    joint: body_to_thruster_left
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_thruster_controller:
    type: effort_controllers/JointEffortController
    joint: body_to_thruster_right
    pid: {p: 100.0, i: 0.01, d: 10.0}